const indianBanksEnum = [
  // Public Sector Banks
  "State Bank of India",
  "Punjab National Bank",
  "Bank of Baroda",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",

  // Private Sector Banks
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC First Bank",
  "Federal Bank",
  "South Indian Bank",
  "RBL Bank",
  "City Union Bank",
  "Karur Vysya Bank",
  "Tamilnad Mercantile Bank",
  "DCB Bank",
  "CSB Bank",
  "Jammu & Kashmir Bank",
  "Karnataka Bank",
  "Bandhan Bank",
  "IDBI Bank",
  "Lakshmi Vilas Bank",

  // Small Finance Banks
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Jana Small Finance Bank",
  "Suryoday Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "ESAF Small Finance Bank",
  "North East Small Finance Bank",
  "Capital Small Finance Bank",
  "Unity Small Finance Bank",
  "Shivalik Small Finance Bank",

  // Payments Banks
  "Airtel Payments Bank",
  "India Post Payments Bank",
  "Paytm Payments Bank",
  "Fino Payments Bank",
  "Jio Payments Bank",

  // Foreign Banks in India
  "Citibank",
  "HSBC Bank",
  "Standard Chartered Bank",
  "Deutsche Bank",
  "Barclays Bank",
  "BNP Paribas",
  "Credit Suisse",
  "UBS",
  "DBS Bank",
  "Bank of America",
  "JPMorgan Chase Bank",
  "MUFG Bank",
  "Mizuho Bank",
  "Sumitomo Mitsui Banking Corporation",
  "Societe Generale",
  "Doha Bank",
  "Qatar National Bank",
  "Emirates NBD Bank",
  "Abu Dhabi Commercial Bank",
  "Mashreq Bank",
];

export default indianBanksEnum;
